### ISSUE TITLE
error: 'Ping' was not declared in this scope

### ISSUE THREAD

**Issue by simkard69** [dvarrel/ESP_Ping#1]
Hello,

Seems like I can't get the example to compile as I'm getting the following error message :
`error: 'Ping' was not declared in this scope`

Any idea ?

In the meantime, I've switched back to this library : [https://github.com/marian-craciunescu/ESP32Ping](url)

**Comment by dvarrel** [comment]
Hi,
have you got release 1.0.0 or 1.0.1 ? 1.0.0 have a compilation problem with windows ( not linux, who is sensitive case with files )

**Comment by dvarrel** [comment]
correct code in 1.0.1
