### ISSUE TITLE
One free too many

### ISSUE THREAD

**Issue by BojanJurca** [dvarrel/ESP_Ping#10]
Hello,

First I would like to thank you for a useful class. I noticed  a bug, however.

In the following piece of code mem_freee is too much, since the memory could not have been allocated:

```C++
    iecho = (struct icmp_echo_hdr *)mem_malloc((mem_size_t)ping_size);
    if (!iecho) {
mem_free(iecho);    
        return ERR_MEM;
    }
```

This would probably just crash the ESP32 if executed.

**Comment by dvarrel** [comment]
[https://cplusplus.com/reference/cstdlib/free/](https://cplusplus.com/reference/cstdlib/free/)

it will do nothing no ?

**Comment by BojanJurca** [comment]
Indeed. Thank you for letting me know,


V V pon., 8. apr. 2024 ob 04:10 je oseba dam74 ***@***.***>
napisala:
