### ISSUE TITLE
if( Ping.ping("www.google.com")) -- doesnt wait for ping response

### ISSUE THREAD

**Issue by nikkdevic** [dvarrel/ESP_Ping#2]
This doesnt work. It doesnt wait for ping response.
`if( Ping.ping("www.google.com"))`

This works for now -
```
bool pingstate = Ping.ping("www.google.com");
delay(500);
float avg_time_ms = 0;
avg_time_ms = Ping.averageTime();
if (avg_time_ms)
```

**Comment by nikkdevic** [comment]
Also Can you add Home Button to return to main page and 'Done' message after upload is done.

**Comment by dvarrel** [comment]
sorry , i don't understand your last comment

**Comment by nikkdevic** [comment]
sorry accidentally posted that in wrong place

**Comment by dvarrel** [comment]
pb with yield() and esp8266
