### ISSUE TITLE
Too many compilation errors

### ISSUE THREAD

**Issue by Advocate-Sandeep-Prakash** [dvarrel/ESP_Ping#3]
Here are the errors that I get while compiling in VSCode + PlatformIO

`.pio/libdeps/nodemcuv2/ESPping/src/ESPping.h:62:5: error: 'ping_option' does not name a type`

`.pio/libdeps/nodemcuv2/ESPping/src/ESPping.cpp:37:17: error: 'INT_MAX' was not declared in this scope`

`.pio/libdeps/nodemcuv2/ESPping/src/ESPping.cpp:42:13: error: '_options' was not declared in this scope`

`.pio/libdeps/nodemcuv2/ESPping/src/ESPping.cpp:42:51: error: invalid application of 'sizeof' to incomplete type 'PingClass::ping(IPAddress, unsigned int)::ping_option'`

And many more along with `error: 'Ping' was not declared in this scope`

**Comment by Advocate-Sandeep-Prakash** [comment]
Additional information: I am on Linux 

lib_deps=dvarrel/ESPping @ ^1.0.1

**Comment by dvarrel** [comment]
i have no compilation errors with arduino 2 or 1.8. I am on linux too, and i've tested on windows
you're on esp32 or esp8266 ?

**Comment by dvarrel** [comment]
you're on esp32 or esp8266 ?

**Comment by dvarrel** [comment]
i tested with platformio, it succeed :
`Building .pio/build/wemos_d1_uno32/firmware.bin
esptool.py v4.4
Creating esp32 image...
Merged 25 ELF sections
Successfully created esp32 image.
================================================== [SUCCESS] Took 9.41 seconds ==================================================`
