### ISSUE TITLE
ping status always 1

### ISSUE THREAD

**Issue by Olivierbkk** [dvarrel/ESP_Ping#4]
Hello,

if my intenet connection is down, I get this:

```
8.8.8.8 response time : 0/0.00/0ms
pingSate : 1
```

where pingState is defined by

`bool pingState = Ping.ping(remote_ip);`

shouldn't this print "error"?

if internet is connected it returns proper response time, for example:

```
8.8.8.8 response time : 29/29.16/29ms
pingState : 1
```

here is the code I use:

```C++
      const IPAddress remote_ip(8,8,8,8);
      bool pingState = Ping.ping(remote_ip);
      
      Serial.print(remote_ip);
      
      if (Ping.ping(remote_ip)){
        Serial.printf(" response time : %d/%.2f/%d", Ping.minTime(), Ping.averageTime(), Ping.maxTime());
        Serial.println("ms");
        Serial.print("pingState : ");
        Serial.println(pingState);
      } else {
        Serial.println(" Error !");
      }
```

**Comment by SamZaitcev** [comment]
I have the same thing, but always get 0.

```
        bool pret = Ping.ping("google.com");
        Serial.print("PRET: ");
        Serial.println(pret);
```

**Comment by dvarrel** [comment]
there is a problem with yield() with esp8266.
can you try the new code

**Comment by Olivierbkk** [comment]
Hello,
I am using the 1.0.1 version of the library, is there a newer code?
I am using on ESP32

**Comment by dvarrel** [comment]
yes, the main branch.
I've tested with esp8266 and also esp32

**Comment by SamZaitcev** [comment]
It's working in version 1.0.2!

**Comment by dvarrel** [comment]
ok, i published it
