### ISSUE TITLE
cluttered debug terminal

### ISSUE THREAD

**Issue by Selene53** [dvarrel/ESP_Ping#6]
Is there any chance of turning off the serial debugging, I'm getting a lot of chatter in my already cluttered debug terminal

xping 1, timeout 0, total payload 32 bytes, 1005 ms
xping 1, timeout 0, total payload 32 bytes, 1010 ms
xping 1, timeout 0, total payload 32 bytes, 1021 ms
ping 1, timeout 0, total payload 32 bytes, 1008 ms
xping 1, timeout 0, total payload 32 bytes, 1019 ms
xping 1, timeout 0, total payload 32 bytes, 1004 ms
xping 1, timeout 0, total payload 32 bytes, 1013 ms

thanks

**Comment by dvarrel** [comment]
Hi,
it's in esp8266 package
file esp-ping.c line 252    in folder esp8266/tools/sdk/lwip2

you have to re-compile it, so you must install with git :
https://arduino-esp8266.readthedocs.io/en/latest/installing.html#using-git-version
