### ISSUE TITLE
Quiet mode, please?

### ISSUE THREAD

**Issue by SteveRMann** [dvarrel/ESP_Ping#7]
I just want a simple response if the target is present or not:
if (Ping.ping(remote_ip) == 0){

I DO NOT want the library to print other data to my stdout:
"ping 5, timeout 0, total payload 160 bytes, 5098 ms"

If I want to see that, then it should be up to me, not the library.

**Comment by dvarrel** [comment]
these debug data are not in my library...

see here : https://github.com/dvarrel/ESPping/issues/6
