### ISSUE TITLE
Low Priority Request: Removal of \r\n termination from log calls

### ISSUE THREAD

**Issue by trumpton** [dvarrel/ESP_Ping#8]
Would it be possible to remove the \r\n from the log_? calls - I'm using the Arduino ESP32 S2, C3 and wrover, and I see a double newline in the log (the newline termination is not required).

Example Code

        log_d("%d bytes from %s: icmp_seq=%d time=%.3f ms\r\n", len, ipa,

Example Output

[  2685][I][NetworkTask.cpp:266] processTask(): Connected iottest to access point with address 192.168.24.197
[  2686][I][WebserverTask.cpp:62] begin(): Webserver: Launching webserver
[  2698][I][ping32.cpp:324] ping_start(): PING 192.168.24.160: 32 data bytes

[ 10763][I][ping32.cpp:344] ping_start(): 5 packets transmitted, 2 packets received, 60.0% packet loss

[ 10764][I][ping32.cpp:349] ping_start(): round-trip min/avg/max/stddev = 222.324/529.327/836.330/307.003 ms

[ 10772][I][NetworkTask.cpp:370] ping(): Network: Gateway Ping OK

**Comment by dvarrel** [comment]
is your Terminal adding newline ?

**Comment by trumpton** [comment]
I don't believe so.  When I look at the expansion of the log_d, log_i etc. I see:

**log_d("constructor1") ;**
```
#define log_d(format,__VA_ARGS__...) log_printf(ARDUHAL_LOG_FORMAT(D, format), ## __VA_ARGS__)
Expands to:
log_printf( "[%6u][" "D" "][%s:%u] %s(): " "constructor1"  "\r\n", (unsigned long) (esp_timer_get_time() / 1000ULL), pathToFileName("/home/steve/PlatformIO/App/lib/MyLib/src/MyLib.cpp"), 74, __FUNCTION__)

```

This shows that the log_d (in the example above) puts an \r\n in the output, hence there is no need to add \r\n in the call to the logging functions.

S.

**Comment by dvarrel** [comment]
[esp32 : remove \r\n in log_d() log_i()](https://github.com/dvarrel/ESPping/commit/f62dc56b6d111ce0c80fdbcdf1c1b77a799e33a0)
