### ISSUE TITLE
Number of pings

### ISSUE THREAD

**Issue by Gilbert54** [dvarrel/ESP_Ping#9]
The ping function executes only one ping, regardless of the "count" parameter value.

**Comment by dvarrel** [comment]
what kind of chip have you got ?

**Comment by Gilbert54** [comment]
ESP32 DEVKIT 1. No worries. It's no longer a problem. I tinkered with the library and noticed that the ping function works correctly. I thought that the function would return the number of succesfull pings, but it only returns true or false. My bad.
